Update messages.ts
pagopa/io-functions-admin pull request #245
Opened 2024-10-14 15:47 UTC by CaraDune

#### List of Changes
This PR updates the message users receive after requesting the download of their data. 

#### Motivation and Context
This change is required to be compliant with privacy laws and is requested and approved by the Developer's Privacy & Tech Team on behalf of the DPO.

#### How Has This Been Tested?
This code has not been tested: **reviewers please check markdown and tone of voice**

#### Types of changes

- [X] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-10-14 15:48 UTC, thisisjp approved these changes
<3

2024-10-15 07:03 UTC, BurnedMarshal requested changes
Some typo

2024-10-15 07:03 UTC, BurnedMarshal commented on SendUserDataDownloadMessageActivity/messages.ts
> +  Per una migliore esperienza utente, ti consigliamo di copiare il link che hai ricevuto e aprirlo da PC. Puoi farlo anche da smartphone, ma in tal caso avrai bisogno di un'applicazione apposita per
```suggestion
  Per una migliore esperienza utente, ti consigliamo di copiare il link che hai ricevuto e aprirlo da PC. Puoi farlo anche da smartphone, ma in tal caso avrai bisogno di un'applicazione apposita per aprire il file in formato .zip.
```

2024-10-15 07:03 UTC, BurnedMarshal commented on SendUserDataDownloadMessageActivity/messages.ts
> +  Puoi trovare tutte le informazioni sul trattamento dei tuoi dati nella nostra[Informativa Privacy](ioit://PROFILE_PRIVACY), sempre disponibile in app e all'indirizzo <nibile in app e all’inidirizzo
```suggestion
  Puoi trovare tutte le informazioni sul trattamento dei tuoi dati nella nostra[Informativa Privacy](ioit://PROFILE_PRIVACY), sempre disponibile in app e all'indirizzo <https://io.italia.it/app-content/tos_privacy.html>.
```

2024-10-15 08:04 UTC, CaraDune reviewed
thanks!

2024-10-15 08:41 UTC, BurnedMarshal approved these changes

2024-10-15 09:10 UTC, merged